### ISSUE TITLE
Add min-height to .megakrill class...

### ISSUE THREAD

**Issue by mhulse** [mhulse/jquery-megakrill#2]
``` css
/*
**--------------------------------------------------------------------------
**
** Mobile menu:
**
**--------------------------------------------------------------------------
*/

/*
**----------------------------------
** Main wrapper div:
**----------------------------------
*/

.megakrill {
    min-height: 49px;
    _height: 49px;
    width: 100%;
    float: left;
}
```

**Comment by mhulse** [comment]
Also added `display: inline;`:

``` css
.megakrill {
    min-height: 49px;
    _height: 49px;
    width: 100%;
    float: left;
    display: inline;
}
```
