### ISSUE TITLE
When javascript is disabled...

### ISSUE THREAD

**Issue by mhulse** [mhulse/jquery-megakrill#3]
... stop the `<h1>` from overlapping the navigation:

``` css
/* If javascript is turned off, tidy things up: */
.no-js h1 {
    position: static;
    margin-bottom: 10px;
}
```

... obviously, put the above in `demo.css`.
